[package]
name = "tomt_youtube"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }

[dependencies]
reqwest = { version = "0.11.23" }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.56"
